"""Initial

Revision ID: 044205ef40c3
Revises: 
Create Date: 2026-07-29 19:40:50.453107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044205ef40c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('empid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('empnumber', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('doj', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('shifthours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('empid')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_empid'), 'employees', ['empid'], unique=False)
    op.create_index(op.f('ix_employees_empnumber'), 'employees', ['empnumber'], unique=True)
    op.create_table('leave_types',
    sa.Column('lvid', sa.Integer(), nullable=False),
    sa.Column('lvname', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('lvid')
    )
    op.create_index(op.f('ix_leave_types_lvid'), 'leave_types', ['lvid'], unique=False)
    op.create_table('attendance',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('empid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('punch_in', sa.Time(), nullable=True),
    sa.Column('punch_out', sa.Time(), nullable=True),
    sa.Column('hours_worked', sa.Interval(), nullable=True),
    sa.Column('punch_in_photo', sa.String(), nullable=True),
    sa.Column('punch_out_photo', sa.String(), nullable=True),
    sa.Column('punch_in_latitude', sa.Float(), nullable=True),
    sa.Column('punch_in_longitude', sa.Float(), nullable=True),
    sa.Column('punch_out_latitude', sa.Float(), nullable=True),
    sa.Column('punch_out_longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empid'], ['employees.empid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_attendance_aid'), 'attendance', ['aid'], unique=False)
    op.create_table('leave',
    sa.Column('laid', sa.Integer(), nullable=False),
    sa.Column('lvid', sa.Integer(), nullable=True),
    sa.Column('empid', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empid'], ['employees.empid'], ),
    sa.ForeignKeyConstraint(['lvid'], ['leave_types.lvid'], ),
    sa.PrimaryKeyConstraint('laid')
    )
    op.create_index(op.f('ix_leave_laid'), 'leave', ['laid'], unique=False)
    op.create_table('leave_balance',
    sa.Column('lbid', sa.Integer(), nullable=False),
    sa.Column('lvid', sa.Integer(), nullable=True),
    sa.Column('empid', sa.Integer(), nullable=True),
    sa.Column('start_bal', sa.Integer(), nullable=True),
    sa.Column('used_bal', sa.Integer(), nullable=True),
    sa.Column('leave_balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empid'], ['employees.empid'], ),
    sa.ForeignKeyConstraint(['lvid'], ['leave_types.lvid'], ),
    sa.PrimaryKeyConstraint('lbid')
    )
    op.create_index(op.f('ix_leave_balance_lbid'), 'leave_balance', ['lbid'], unique=False)
    op.create_table('payroll',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('empid', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('paid_days', sa.Integer(), nullable=True),
    sa.Column('net_pay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empid'], ['employees.empid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_payroll_pid'), 'payroll', ['pid'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('empid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empid'], ['employees.empid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payroll_pid'), table_name='payroll')
    op.drop_table('payroll')
    op.drop_index(op.f('ix_leave_balance_lbid'), table_name='leave_balance')
    op.drop_table('leave_balance')
    op.drop_index(op.f('ix_leave_laid'), table_name='leave')
    op.drop_table('leave')
    op.drop_index(op.f('ix_attendance_aid'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_leave_types_lvid'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_employees_empnumber'), table_name='employees')
    op.drop_index(op.f('ix_employees_empid'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
