"""Remaks column in LeaveApplication

Revision ID: 48b65ba76afc
Revises: 6300194402d0
Create Date: 2026-08-03 14:36:18.399966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b65ba76afc'
down_revision: Union[str, Sequence[str], None] = '6300194402d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave', 'remarks')
    # ### end Alembic commands ###
