"""rename and add column

Revision ID: 4f88fa4d4830
Revises: 044205ef40c3
Create Date: 2026-08-01 11:34:39.455096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f88fa4d4830'
down_revision: Union[str, Sequence[str], None] = '044205ef40c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balance', sa.Column('opening_bal', sa.Integer(), nullable=True))
    op.add_column('leave_balance', sa.Column('accured_bal', sa.Integer(), nullable=True))
    op.drop_column('leave_balance', 'start_bal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balance', sa.Column('start_bal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('leave_balance', 'accured_bal')
    op.drop_column('leave_balance', 'opening_bal')
    # ### end Alembic commands ###
