"""reportingmanager column in employee

Revision ID: 6300194402d0
Revises: fba34d644496
Create Date: 2026-08-03 14:20:40.305461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6300194402d0'
down_revision: Union[str, Sequence[str], None] = 'fba34d644496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('reporting_manager_empid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'reporting_manager_empid')
    # ### end Alembic commands ###
