"""New Column in leavebal

Revision ID: 6c016e1b9a12
Revises: 48b65ba76afc
Create Date: 2026-08-04 08:52:35.284696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c016e1b9a12'
down_revision: Union[str, Sequence[str], None] = '48b65ba76afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balance', sa.Column('reserved_bal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_balance', 'reserved_bal')
    # ### end Alembic commands ###
