"""gross column in payroll

Revision ID: 9ade0489289d
Revises: 6c016e1b9a12
Create Date: 2026-08-05 11:03:07.088392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ade0489289d'
down_revision: Union[str, Sequence[str], None] = '6c016e1b9a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll', sa.Column('gross_salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll', 'gross_salary')
    # ### end Alembic commands ###
