"""removed col in leavebal

Revision ID: b17929e0131f
Revises: 4f88fa4d4830
Create Date: 2026-08-01 15:03:26.163967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17929e0131f'
down_revision: Union[str, Sequence[str], None] = '4f88fa4d4830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_balance', 'leave_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balance', sa.Column('leave_balance', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
