"""

Revision ID: f137400b35e3
Revises: ca9624368d95
Create Date: 2026-08-27 11:03:12.648609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f137400b35e3'
down_revision: Union[str, Sequence[str], None] = 'ca9624368d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('empnumber', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_empnumber'), 'users', ['empnumber'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_empnumber'), table_name='users')
    op.drop_column('users', 'empnumber')
    # ### end Alembic commands ###
